### POSTGRESQL ###
spring :
  datasource :
    url : jdbc:postgresql://localhost:5433/my_db
    username: postgres
    password: Hiphop!87
    tomcat:
      max-idle: 10
      min-idle: 1
      initial-size: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate :
        dialect: org.hibernate.dialect.PostgreSQLDialect
